---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[SEC] "
      include: "scope"
    assignees:
      - "bilbu"
    ignore:
      - dependency-name: "clap"
        update-types: ["version-update:semver-major"]
